SRCDIR = $(realpath .)
TOPDIR = $(realpath ../..)

include $(TOPDIR)/Make.version
include $(TOPDIR)/Make.rules
include $(TOPDIR)/Make.defaults

#install:
#	$(INSTALL) -d -m 755 $(INSTALLROOT)$(PREFIX)/include/libdpe/
#	$(INSTALL) -m 644 *.h $(INSTALLROOT)$(PREFIX)/include/libdpe/
