.TH AUTHVAR "1" "June 2015"
.SH NAME
authvar \- handles authenticated variables for pesign

.SH SYNOPSIS
\fBauthvar\fR [\-?] [\-a|\-\-append] [\-d|\-\-certdir=<certificate directory path>]
        [\-c|\-\-clear] [\-s|\-\-set] [\-N|\-\-namespace={<namespace>|<guid>}]
        [\-n|\-\-name=<name>] [\-t|\-\-timestamp=<time>] [\-v|\-\-value=<value>]
        [\-f|\-\-valuefile=<file>] [\-i|\-\-import=<file>] [\-e|\-\-export=<file>]
        [\-S|\-\-sign=<nickname>] [\-?|\-\-help] [\-\-usage]

.SH DESCRIPTION
\fBauthvar\fR is a command line utility for handling authenticated UEFI variables.

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-append\fR
append to variable

.TP
\fB\-d\fR, \fB\-\-certdir=\fR<certificate directory path>
specify nss certificate
database directory (default:
"/etc/pki/pesign")

.TP
\fB\-c\fR, \fB\-\-clear\fR
clear variable

.TP
\fB\-s\fR, \fB\-\-set\fR
set variable

.TP
\fB\-N\fR, \fB\-\-namespace=\fR{<namespace>|<guid>}
specified variable is in
<namespace> or <guid>
(default: "global")

.TP
\fB\-n\fR, \fB\-\-name=\fR<name>
variable name

.TP
\fB\-t\fR, \fB\-\-timestamp=\fR<time>
timestamp for the variable

.TP
\fB\-v\fR, \fB\-\-value=\fR<value>
value to set or append

.TP
\fB\-f\fR, \fB\-\-valuefile=\fR<file>
read value from <file>

.TP
\fB\-i\fR, \fB\-\-import=\fR<file>
import variable from <file>

.TP
\fB\-e\fR, \fB\-\-export=\fR<file>
export variable to <file>
instead of firmware

.TP
\fB\-S\fR, \fB\-\-sign=\fR<nickname>
sign variable with
certificate <nickname>

.SS "Help options:"

.TP
\-?, \fB\-\-help\fR
Show this help message

.TP
\fB\-\-usage\fR
Display brief usage message

.SH "SEE ALSO"
.BR pesign (1)
