.TH EFISIGLIST "1" "June 2015"
.SH NAME
efisiglist \- utility for managing UEFI signature lists

.SH SYNOPSIS
\fBefisiglist\fR [\-?] [\-o|\-\-outfile=<outfile>] [\-a|\-\-add] [\-r|\-\-remove]
        [\-h|\-\-hash=<hash>] [\-t|\-\-hash\-type=<hash\-type>]
        [\-c|\-\-certificate=<certfile>] [\-?|\-\-help] [\-\-usage]

.SH DESCRIPTION
\fBefisiglist\fR is a command line utility for management of UEFI signature lists
in detached files. That is, it's for command line generation and management of files in
the format of KEK, DB, and DBX.

.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-outfile=\fR<outfile>
output filename

.TP
\fB\-a\fR, \fB\-\-add\fR
add hash or certificate to list

.TP
\fB\-r\fR, \fB\-\-remove\fR
remove hash or certificate from list

.TP
\fB\-h\fR, \fB\-\-hash=\fR<hash>
hash value to add

.TP
\fB\-t\fR, \fB\-\-hash\-type=\fR<hash\-type>
hash type to add (default: "sha256")

.TP
\fB\-c\fR, \fB\-\-certificate=\fR<certfile>
certificate to add
.PP
Options implemented via popt alias/exec:
.SS "Help options:"
.TP
\-?, \fB\-\-help\fR
Show this help message
.TP
\fB\-\-usage\fR
Display brief usage message

.SH "SEE ALSO"
.BR pesign (1)
