.TH pesigcheck 1 "Mon Sep 10 2012"
.SH NAME
pesign \- command line tool for verifying UEFI applications

.SH SYNOPSIS
\fBpesign\fR [--in=\fIinfile\fR | -i \fIinfile\fR] [--quiet | -q ]
       [--db=\fIdbfile\fR | -D \fIdbfile\fR ]
       [--dbx=\fIdbxfile\fR | -X \fIdbxfile\fR ]

.SH DESCRIPTION
\fBpesigcheck\fR is a command line tool for verifying the signature of UEFI
applications.

.SH OPTIONS
.TP
\fB-\-in\fR=\fIinfile\fR
Specify input binary.

.SH "SEE ALSO"
.BR pesigcheck (1)

.SH AUTHORS
.nf
Peter Jones
.fi
