#!/bin/bash
set -e
set -u

# License: GPLv2

# This script is deprecated and will be removed in a future release.

sleep 3
for x in /var/run/pesign/ /etc/pki/pesign/ ; do
	chown -R pesign:pesign "${x}" || true
	chmod -R ug+rwX "${x}" || true
done
