#!/bin/bash

#
# With /run/pesign/socket on tmpfs, a simple way of restoring the
# acls for specific users is useful
#
#  Compare to: http://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/bkernel/tasks/main.yml?id=17198dadebf59d8090b7ed621bc8ab22152d2eb6
#

# License: GPLv2

if [[ -r /etc/pesign/users ]]; then
    for username in $(cat /etc/pesign/users); do
	if [ -d /var/run/pesign ]; then
	    setfacl -m u:${username}:rx /var/run/pesign
	    if [ -e /var/run/pesign/socket ]; then
		setfacl -m u:${username}:rw /var/run/pesign/socket
	    fi
	fi
	if [ -d /etc/pki/pesign ]; then
	    setfacl -m u:${username}:rx /etc/pki/pesign
	    setfacl -m u:${username}:r /etc/pki/pesign/{cert8,key3,secmod}.db
	fi
    done
fi
