#!/bin/bash
set -e
set -u

#
# With /run/pesign/socket on tmpfs, a simple way of restoring the
# acls for specific users is useful
#
#  Compare to: http://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/bkernel/tasks/main.yml?id=17198dadebf59d8090b7ed621bc8ab22152d2eb6
#

# License: GPLv2
declare -a fileusers=()
declare -a dirusers=()
while read -r user ; do
	dirusers[${#dirusers[@]}]=-m
	dirusers[${#dirusers[@]}]="u:$user:rwx"
	fileusers[${#fileusers[@]}]=-m
	fileusers[${#fileusers[@]}]="u:$user:rw"
done </etc/pesign/users

declare -a filegroups=()
declare -a dirgroups=()
while read -r group ; do
	dirgroups[${#dirgroups[@]}]=-m
	dirgroups[${#dirgroups[@]}]="g:$group:rwx"
	filegroups[${#filegroups[@]}]=-m
	filegroups[${#filegroups[@]}]="g:$group:rw"
done </etc/pesign/groups

update_subdir() {
	subdir=$1 && shift

	setfacl -bk "${subdir}"
	setfacl "${dirusers[@]}" "${dirgroups[@]}" "${subdir}"
	for x in "${subdir}"* ; do
		if [ -d "${x}" ]; then
			setfacl -bk "${x}"
			setfacl "${dirusers[@]}" "${dirgroups[@]}" "${x}"
			update_subdir "${x}/"
		elif [ -e "${x}" ]; then
			setfacl -bk "${x}"
			setfacl "${fileusers[@]}" "${filegroups[@]}" "${x}"
		else
			:;
		fi
	done
}

sleep 3
for x in /etc/pki/pesign/ /var/run/pesign/ ; do
	if [ -d "${x}" ]; then
		update_subdir "${x}"
	else
		:;
	fi
done
